
import {
    IonCard,
    IonRouterOutlet,
    IonItemOption,
    IonHeader,
    IonToolbar,
    IonButtons,
    IonBackButton,
    IonTitle,
    IonContent,
    IonButton,
    IonIcon,
    IonFooter,
    IonItemOptions,
    IonLabel,
    IonItem,
    IonItemSliding,
    IonList,
    IonCardContent,
    IonCardTitle,
    IonCardHeader,
    IonText,
    IonCol,
    IonRow,
    IonGrid,
    IonSearchbar
} from '@ionic/angular/standalone';

export const imports = [
    IonCard,
    IonRouterOutlet,
    IonItemOption,
    IonHeader,
    IonToolbar,
    IonButtons,
    IonBackButton,
    IonTitle,
    IonContent,
    IonButton,
    IonIcon,
    IonFooter,
    IonItemOptions,
    IonLabel,
    IonItem,
    IonItemSliding,
    IonList,
    IonCardContent,
    IonCardTitle,
    IonCardHeader,
    IonText,
    IonCol,
    IonRow,
    IonGrid,
    IonSearchbar,

]